@startuml

title Smart House Device Service Component Diagram

top to bottom direction

!include ../c4-local/C4-Component.puml

Container_Boundary(DeviceService, "Device Service") {

    Component(RegistrationController, "Контроллер регистрации", "Обрабатывает запросы регистрации устройств")

    Component(ConnectionController, "Контроллер подключения", "Обрабатывает запросы подключения и настройки устройств")

    Component(DeviceController, "Контроллер устройств", "Обрабатывает запросы управления устройствами")

    Component(ServiceLayer, "Сервисный слой", "Бизнес-логика")

    Component(DataAccessLayer, "Слой доступа к данным", "Работа с данными и настройками устройств")
}

ContainerDb(DeviceDb, "БД Устройств", "PostgreSQL", "Хранение и обработка данных и настроек устройств")

Container(DeviceIntegrationService, "Сервис Интеграции Устройств", "Go", "Интеграция с устройствами партнеров по стандартным протоколам")

Rel(RegistrationController, ServiceLayer, "Вызывает бизнес-логику")
Rel(ConnectionController, ServiceLayer, "Вызывает бизнес-логику")
Rel(DeviceController, ServiceLayer, "Вызывает бизнес-логику")

Rel(ServiceLayer, DataAccessLayer, "Читает и изменяет данные")

Rel(DataAccessLayer, DeviceDb, "Читает и сохраняет данные устройств", "PostgreSQL")

Rel(ServiceLayer, DeviceIntegrationService, "Регистрирует и настраивает устройства")

@enduml